### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by Jerrodly** [lugia-ysstech/mega-cli#22]
就反馈几个问题：
1、lerna bootstrap 运行不成功，没有下载package中的依赖包，解决方案：在package.json中添加"workspaces": ["packages/*"],而且需要在lerna.json中添加 "useWorkspaces": true,这样就可以解决了
2、就是运行单个包的命令会报错：yarn run lerna exec --scope mega-webpack -- yarn run test

**Comment by grguang** [comment]
第一个问题，经排查没有发现lerna bootstrap 运行不成功的问题，第二个问题参照最新的README.md 运行命令。
